org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
jei_version=15.20.0.115
jade_id=4986594
ae_id=7125328
pe_id=4901949
curios_id=6418456
mixin_version=0.8.5
mmmm_id=6860192
ye_id=7108732

mapping_channel=official
mapping_version=1.20.1
mod_id=spacearms
mod_name=SpaceArms
mod_license=MIT
mod_version=1.20.1-0.2
mod_group_id=com.yuo
mod_authors=yuo
mod_description=SpaceArms 1.20.1.