modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]] #mandatory
modId="spacearms" 
version="1.16.5-1.4.6"
displayName="SpaceArms"
authors="yuo" 
description='''
强力装备。1.16.5
'''
[[dependencies.spacearms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5, 1.17)"
    ordering="NONE"
    side="BOTH"
